### ISSUE TITLE
Changes to be done.

### ISSUE THREAD

**Issue by Abhi-1198-zz** [saranonearth/NCICEC_Website#15]
- [x]  Change NCICEC '19 to NCICEC 2019 in header.
- [x] Increase the font size of 26th National Conference on Internal Combustion Engines and Combustion.
- [x] Capitalize D in Important dates.
- [x] Center the Heading & Table Important Dates.
- [x] One field remaining in Important details- Look it in Important dates table in Brochure. 
- [x] Material Synthesis is written two times in Conference themes. 
- [x] Restructure call for papers to format  -----> (Call for papers---->Submission Guidelines------>Themes---> Important Mentions( From the brochure on Important dates page))

> _Submission Guidelines:  All papers must be original and not simultaneously submitted to another journal or conference. All papers will be reviewed by Technical Review Committee members and other experts active in the field to ensure high quality and relevance to the conference. Submissions should include title, abstract, 5-10 keywords, and be in PDF format. Each submission must not exceed 8 pages in the Springer publications format with 10 point font, including tables, figures, and references. All submitted papers will be subjected to a "Plagiarism check" by Turnitin Software. Papers achieving less than 20% similarity score will only be sent for the formal review._

- [x]  Centre float all entries in registration page table
- [x]  Change Plenary speakers to coming soon instead of Coming Soon.
- [x]  Improve formatting of Registration page
- [x] Add easy chair link in call for papers tab.
- [x] Update cards with info in sponsorship opportunities tab.
- [x] Change lorem ipsum in Sponsorship benefits to text from brochure.
- [x]  Change text in Sponsorship Opportunities
- [x] Change font size of Footer "Organised by"
- [x] Change in association with CIIS 
- [x] Change Nit Kurukshetra to open link in new tab
- [x] Remove QR Code from contact page
- [x] Change numbers in Conference Secretriat tab.
- [x] Recheck Committees if it's working properly

**Comment by prathamzx** [comment]
easy chair link??

**Comment by Abhi-1198-zz** [comment]
Closing the Issue
