### ISSUE TITLE
Work to be done 

### ISSUE THREAD

**Issue by Abhi-1198-zz** [saranonearth/NCICEC_Website#2]
- [x] Create the Home page
- [x] About
- [x] Important Dates
- [x] Venue 
- [x] Paper Submission
- [x] Registration
- [x] Plenary speakers
- [x] Sponsors
- [x] Committees
- [x] Downloads
- [x] Gallery
- [x] Contact

**Comment by saranonearth** [comment]
Working on Homepage

**Comment by Abhi-1198-zz** [comment]
Working on Registration Page

**Comment by Abhi-1198-zz** [comment]
@prathamzx  make a page from the list.

**Comment by prathamzx** [comment]
Working on about page

**Comment by saranonearth** [comment]
working on contact page

**Comment by saranonearth** [comment]
working on gallery

**Comment by prathamzx** [comment]
working on committees

**Comment by Abhi-1198-zz** [comment]
working on Important Dates page
